#pragma once

#include <cstdint>

namespace Game {

enum SurfaceType : uint8_t {
	SURFACE_TYPE_SMOOTH = 0,
	SURFACE_TYPE_GLUE = 1,
	SURFACE_TYPE_WELD = 2,
	SURFACE_TYPE_STUDS = 3,
	SURFACE_TYPE_INLET = 4,
	SURFACE_TYPE_UNIVERSAL = 5,
	SURFACE_TYPE_HINGE = 6,
	SURFACE_TYPE_MOTOR = 7,
	SURFACE_TYPE_STEPPING_MOTOR = 8,
	SURFACE_TYPE_SMOOTH_NO_OUTLINES = 10
};

}

